name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install AWS CLI
      run: |
        npm install -g aws-cli

    - name: GOKHAN
      run: |
        echo "gokhan kocturkkk"
        
    - name: Deploy CloudFormation
      run: |
        aws cloudformation deploy --template-file deneme.yaml --stack-name yaml-latestami
